AttackAPI.Signatures = {};
AttackAPI.Signatures.extensions = [
	{ name: 'Adblock Plus', src: 'chrome://adblockplus/skin/adblockplus.png' },
	{ name: 'Auto Copy', src: 'chrome://autocopy/skin/autocopy.png' },
	{ name: 'ColorZilla', src: 'chrome://colorzilla/skin/logo.png' },
	{ name: 'Customize Google', src: 'chrome://customizegoogle/skin/32x32.png' },
	{ name: 'DownThemAll!', src: 'chrome://dta/content/immagini/icon.png' },
	{ name: 'Faster Fox', src: 'chrome://fasterfox/skin/icon.png' },
	{ name: 'Flash Block', src: 'chrome://flashblock/skin/flash-on-24.png' },
	{ name: 'FlashGot', src: 'chrome://flashgot/skin/icon32.png' },
	{ name: 'Forecastfox', src: 'chrome://forecastfox/skin/images/icon.png' },
	{ name: 'Google Toolbar', src: 'chrome://google-toolbar/skin/icon.png' },
	{ name: 'Greasemonkey', src: 'chrome://greasemonkey/content/status_on.gif' },
	{ name: 'IE Tab', src: 'chrome://ietab/skin/ietab-button-ie16.png' },
	{ name: 'IE View', src: 'chrome://ieview/skin/ieview-icon.png' },
	{ name: 'JS View', src: 'chrome://jsview/skin/jsview.gif' },
	{ name: 'Live HTTP Headers', src: 'chrome://livehttpheaders/skin/img/Logo.png' },
	{ name: 'MeasureIt', src: 'chrome://measureit/skin/measureit.png' },
	{ name: 'SEO For Firefox', src: 'chrome://seo4firefox/content/icon32.png' },
	{ name: 'SEOpen', src: 'chrome://seopen/skin/seopen.png' },
	{ name: 'Search Status', src: 'chrome://searchstatus/skin/cax10.png' },
	{ name: 'Server Switcher', src: 'chrome://switcher/skin/icon.png' },
	{ name: 'StumbleUpon', src: 'chrome://stumbleupon/content/skin/logo32.png' },
	{ name: 'Tab Mix Plus', src: 'chrome://tabmixplus/skin/tmp.png' },
	{ name: 'Torrent-Search Toolbar', src: 'chrome://torrent-search/skin/v.png' },
	{ name: 'User Agent Switcher', src: 'chrome://useragentswitcher/content/logo.png' },
	{ name: 'View Source With', src: 'chrome://viewsourcewith/skin/ff/tb16.png' },
	{ name: 'Web Developer', src: 'chrome://webdeveloper/content/images/logo.png' }];
